battlecode/battlecode-server

src/main/battlecode/engine/instrumenter/RoboMethodTree.java

Fixes "Bad &lt;init&gt; method call from after the start of a try block" errors as described in http://www.battlecode.org/contestants/forum/1/42/

fix VerifyErrors

---

src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Resolves https://github.com/battlecode/battlecode-server/issues/158

Archon should not be able to build zombie

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Fixes some bugs / adds some features. See commit messages for issues referenced.

RobotController changes

---

src/main/battlecode/common/ZombieSpawnSchedule.java
src/main/battlecode/instrumenter/bytecode/ClassReferenceUtil.java
src/main/battlecode/world/GameMap.java
src/test/battlecode/instrumenter/IndividualClassLoaderTest.java
src/test/battlecode/instrumenter/sample/instrumentertest/UsesSpawnSchedule.java
src/test/battlecode/world/RobotControllerTest.java

And also re-fix streams and stuff.

Fix issues with ZombieSpawnSchedule by changing its API

---

src/main/battlecode/common/RobotType.java

Also fixed tabbing and spacing in RobotType

More bytecodes for ttm and turret

---

src/main/battlecode/common/RobotType.java

More bytecode

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Addresses https://github.com/battlecode/battlecode-server/issues/144

Improve documentation

---

src/main/battlecode/world/InternalRobot.java

http://battlecodeforum.org/t/self-destruction-and-possible-server-code-bug/103

Fix InternalRobot.takeDamage()

---

src/main/battlecode/common/GameConstants.java
src/main/battlecode/world/InternalRobot.java

Add visibility and reduce chance of inconsistencies.

Define turret transform delay as a game constant

---

README.md

Quick documentation for how to build the battlecode-server.

Add build instructions to README.

---

src/main/battlecode/instrumenter/bytecode/ClassReferenceUtil.java

Addresses an issue @cwgreene discovered in #170.

BREAKING: actually disallow disallowed classes

---

src/main/battlecode/instrumenter/IndividualClassLoader.java
src/main/battlecode/instrumenter/SandboxedRobotPlayer.java
src/main/battlecode/instrumenter/bytecode/ClassReferenceUtil.java
src/main/battlecode/server/ErrorReporter.java
src/main/battlecode/server/Server.java
src/main/battlecode/server/proxy/FileProxy.java
src/main/battlecode/world/GameWorld.java
src/main/battlecode/world/control/PlayerControlProvider.java
src/test/battlecode/instrumenter/IndividualClassLoaderTest.java
src/test/battlecode/instrumenter/sample/instrumentertest/StringFormat.java

We should really just switch to a logging framework...

Better error logging

---

src/main/battlecode/server/Server.java
src/main/battlecode/server/proxy/ProxyWriter.java

Only write to proxies on a single thread

---

src/main/battlecode/instrumenter/bytecode/resources/DisallowedClasses.txt
src/test/battlecode/instrumenter/IndividualClassLoaderTest.java
src/test/battlecode/instrumenter/sample/instrumentertest/Reflection.java

Disable java/lang/Class(Loader)?

---

src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java
src/main/battlecode/instrumenter/bytecode/resources/DisallowedClasses.txt
src/main/battlecode/instrumenter/inject/RobotMonitor.java
src/test/battlecode/instrumenter/IndividualClassLoaderTest.java
src/test/battlecode/instrumenter/sample/instrumentertest/CallsMathRandom.java
src/test/battlecode/instrumenter/sample/instrumentertest/IllegalMethodReference.java
src/test/battlecode/instrumenter/sample/instrumentertest/LegalMethodReference.java
src/test/battlecode/instrumenter/sample/instrumentertest/Reflection.java
src/test/battlecode/instrumenter/sample/instrumentertest/UsesEnumMap.java

Fix reference security whole, add instrumentation tests

---

src/main/battlecode/instrumenter/SandboxedRobotPlayer.java

Pretty simple. I tested it, and messages look like this: "[java] Your GUARD 373 at location [540, 17] died in round 128 because it returned from its run() method!"

Message for return from run()

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Added method to return locations of parts within sense radius, following #189

Part sensing

---

src/main/battlecode/instrumenter/SandboxedRobotPlayer.java
src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java
src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java
src/test/battlecode/instrumenter/sample/testplayerstatic/RobotPlayer.java

And other steps, as necessary.

Count static initialization as part of bytecodes used of player's first step()

---

src/main/battlecode/instrumenter/inject/RobotMonitor.java
src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java
src/test/battlecode/instrumenter/sample/testplayerbytecode/RobotPlayer.java

Enable bytecode overflow over several turns

---

src/main/battlecode/instrumenter/SandboxedRobotPlayer.java
src/main/battlecode/instrumenter/inject/System.java
src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java
src/test/battlecode/instrumenter/sample/testplayersystem/RobotPlayer.java

Enable bc.testing properties

---

src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt

http://battlecodeforum.org/t/bonus-bytecodes/183/1

Set clock boolean values in methodcosts

---

src/main/battlecode/instrumenter/IndividualClassLoader.java
src/main/battlecode/instrumenter/SandboxedRobotPlayer.java
src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java
src/main/battlecode/instrumenter/inject/System.java
src/main/battlecode/server/Config.java
src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java
src/test/battlecode/instrumenter/sample/testplayersystem/RobotPlayer.java

And fix bug with engine crash due to loading multiple robots with illegal players.

Re-enable bc.testing properties

---

src/main/battlecode/world/GameWorld.java
src/test/battlecode/world/RobotControllerTest.java

Addresses https://github.com/battlecode/battlecode-server/issues/215

Archon should pick up parts on tiles it spawns on

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Addresses https://github.com/battlecode/battlecode-server/issues/214

Method to sense initial archon locs

---

src/main/battlecode/common/ZombieSpawnSchedule.java
src/main/battlecode/world/GameMap.java
src/main/battlecode/world/control/ZombieControlProvider.java
src/test/battlecode/common/ZombieSpawnScheduleTest.java

Resolves https://github.com/battlecode/battlecode-server/issues/221

Fix bug with zombie spawn schedule

---

src/main/battlecode/world/GameMap.java
src/test/battlecode/world/GameMapTest.java

Updated isTournamentLegal to check den distance

---

src/main/battlecode/serial/ServerEvent.java
src/main/battlecode/serial/StoredConstants.java
src/main/battlecode/server/Server.java
src/test/battlecode/server/SerializerFactoryTestBase.java

Serialize engine metadata

---

src/main/battlecode/server/Server.java
src/main/battlecode/world/GameMapIO.java
src/test/battlecode/world/GameMapIOTest.java

Resolves https://github.com/battlecode/battlecode-server/issues/235

Allow .xml in map names

---

src/main/battlecode/world/GameWorld.java
src/test/battlecode/world/ZombieControlProviderTest.java

Resolves #238. Test case involves randomness, so there's a 1 to 3 billion chance it may fail.

Added zombie attack randomness

---

src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Fixed senseRobotAtLocation, added test

---

src/main/battlecode/common/Direction.java
src/test/battlecode/world/RobotControllerTest.java

swapped north/south, changed tests

---

src/main/battlecode/common/Direction.java
src/test/battlecode/world/RobotControllerTest.java

Changed Direction specification to be between (-Math.PI, Math.PI]. Added tests.
Resolves #329

Fix directions

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/world/RobotControllerImpl.java

Added rc.getBuildCooldownTurns()

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/world/RobotControllerImpl.java

canChop() now checks for !hasAttacked().
Resolves #332 
Resolves #333

Fix canChop(), remove canInteractWithRobot()

---

src/main/battlecode/server/Server.java
src/main/battlecode/world/DominationFactor.java
src/main/battlecode/world/GameWorld.java
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

Checks victory point threshold with every call of rc.donate(), added a test to ensure this actually works.
Resolves #323

Check victory points

---

src/main/battlecode/schema/Round.java
src/main/battlecode/server/GameMaker.java
src/main/battlecode/world/InternalRobot.java

To display bytecodes used in the client.
https://github.com/battlecode/battlecode-schema/pull/15
https://github.com/battlecode/battlecode-playback/pull/18

Add bytecode usage to flatbuffer

---

src/main/battlecode/instrumenter/bytecode/ClassReferenceUtil.java
src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java
src/test/battlecode/instrumenter/sample/testplayerarray/RobotPlayer.java

Fix parsing of array class name in ClassReferenceUtil.classReference()

---

src/main/battlecode/world/InternalRobot.java
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

You can now shake big trees from inside of them. (Resolves #352)
Also, interaction radius is now stride radius, not body radius. (Resolves #353)
Added test.

shakeshakeshake

---

src/main/battlecode/common/Direction.java
src/test/battlecode/world/RobotControllerTest.java

Resolves #365 
Merge once https://github.com/battlecode/battlecode-client-17/issues/121 is resolved.

Swapped north/south again

---

src/main/battlecode/common/RobotInfo.java

changed doubles to floats in RobotInfo

---

src/main/battlecode/common/GameConstants.java
src/main/battlecode/common/MapLocation.java
src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/common/MapLocationTest.java

Added method and tests for checking if two circles collide.

Colliding circles

---

src/main/battlecode/common/Direction.java
src/test/battlecode/world/RobotControllerTest.java

Fixed reduce() rounding error

---

src/main/battlecode/world/InternalBullet.java

RIP the lumberjack who moved exactly on top of the startLocation of a bullet to discover this bug.

Fixed rare bullet nullPointerException

---

src/main/battlecode/world/GameWorld.java
src/main/battlecode/world/ObjectInfo.java
src/test/battlecode/world/RobotControllerTest.java

Resolves #374 
I'm currently adding tests so hold off for a bit?

Keeps track of robot spawn order and executes robot code in that order

---

src/main/battlecode/common/Direction.java
src/test/battlecode/world/RobotControllerTest.java

Thanks Max.
Added Direction.equals(Direction other), Direction.equals(Direction other, float epsilon), and tests.
Added Direction.NORTH, etc.
Resolves #388 
Resolves #387

Direction.equals(Direction other)

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/common/RobotType.java
src/main/battlecode/world/InternalRobot.java
src/main/battlecode/world/RobotControllerImpl.java
src/test/battlecode/world/RobotControllerTest.java

canWater now returns false on neutral trees, resolves #397 
Gardeners/Archons don't heal for first 20 turns, resolves #396 
Actually use bullet sense radius for bullets 0_0 #394
I just realized I should add tests, so I'll do that now

Dumb bug fixes

---

src/main/battlecode/world/ObjectInfo.java

Should we decide this is how we want to resolve #379

Return nearest objects sorted

---

src/main/battlecode/common/TreeInfo.java

Fix NPE in TreeInfo#hashCode()

---

src/main/battlecode/common/RobotController.java
src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt
src/main/battlecode/world/RobotControllerImpl.java

Added new methods for handling messaging with bools and floats

---

src/main/battlecode/common/RobotType.java
src/test/battlecode/world/RobotControllerTest.java

Make soldier a wee bit slower

---

src/main/battlecode/world/ObjectInfo.java
src/test/battlecode/world/RobotControllerTest.java

Resolves #435 
The added test was able to reproduce the erroneous result (before it was fixed).

fixed getXAtLocation, added tests

---

src/main/battlecode/common/Direction.java

Throw RuntimeExceptions for NaN or Infinity Directions

---

src/main/battlecode/common/GameConstants.java
src/main/battlecode/world/GameWorld.java
src/main/battlecode/world/IDGenerator.java

Resolves #448. Bullets will now take on IDs greater than 32000, but we never said they were bounded.

Use separate IDGenerator for bullets
