battlecode/battlecode-server

src/main/battlecode/engine/instrumenter/RoboMethodTree.java
most of java's stdlib uses the hashcode implementation on the interface, so we can't just blindly put "false" into the instrumentation
=> Fix for constant pool illegal type during hashcode invokeinterface

src/main/battlecode/engine/instrumenter/ClassReferenceUtil.java
This patch replaces the unhelpful error message described in the posts
http://www.battlecode.org/contestants/forum/1/145/
http://www.battlecode.org/contestants/forum/1/150/
with one that lists the file that the game is trying to find.
=> fix unhelpful error message

.gitignore, src/main/battlecode/instrumenter/IndividualClassLoader.java, src/main/battlecode/instrumenter/bytecode/ClassReferenceUtil.java, src/main/battlecode/instrumenter/bytecode/InstrumentingClassVisitor.java, src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java, src/main/battlecode/instrumenter/bytecode/resources/AllowedPackages.txt, src/test/battlecode/instrumenter/IndividualClassLoaderTest.java, src/test/battlecode/instrumenter/sample/instrumentertest/UsesLambda.java
Addresses #141.
Attempts to address #142, but fails because of a new problem: Scanner references Locale, which references JVM-internal classes (sun/), which we don't instrument because it can break things.
Also enables all of the java.util.function and java.util.stream classes, and lambdas (hooray!)
=> Enable lambdas in instrumented java code (and some other Java 8 features)

src/main/battlecode/server/Version.java
Because we're removing version #s on the jars.
=> Add verson command

src/main/battlecode/common/MapLocation.java, src/main/battlecode/common/Signal.java, src/test/battlecode/world/RobotControllerTest.java
Signal.getMessage() now returns a copy of the array, stoping robots from modifying a signal that another one sent (issue #174). I added a test case, which was confirmed failing before fixing the exploit.
Also fixed #173, because it was simple.
=> Message Exploit Fixed

src/main/battlecode/common/GameConstants.java, src/main/battlecode/instrumenter/SandboxedRobotPlayer.java, src/main/battlecode/world/InternalRobot.java, src/main/battlecode/world/RobotControllerImpl.java, src/test/battlecode/world/RobotControllerTest.java
"new messaging restrictions: a message queue can only have 1000 messages maximum (older messages get kicked out). A robot can only send 5 basic signals/turn and 20 message signals/turn.
this is to prevent robots from getting thousands of message in their queue and then emptying it, causing the client to freeze up (this happens)" - David
=> Added messaging restrictions

src/main/battlecode/instrumenter/SandboxedRobotPlayer.java, src/main/battlecode/instrumenter/inject/RobotMonitor.java, src/test/battlecode/instrumenter/SandboxedRobotPlayerTest.java, src/test/battlecode/instrumenter/sample/testplayersuicide/RobotPlayer.java
I was overzealous with "synchronized" annotations, which didn't have *quite* the semantics we wanted.
=> Fix deadlock in disintegrate(), resign(), and when attacking self to death

src/main/battlecode/common/RobotController.java, src/main/battlecode/world/RobotControllerImpl.java, src/test/battlecode/world/RobotControllerTest.java
Fixes https://github.com/battlecode/battlecode-server/issues/193
No delays are accumulated nor are signals sent to the client when an attempt is made to clear rubble off map or on a tile with no rubble.
=> Fix exception with clearing rubble off map

src/main/battlecode/world/GameWorld.java
Stops robots from dying twice sometimes when they attack themselves. Error in #207 was reproduced, and this stops it. Currently doesn't have a test case, but I don't think one is necessary.
=> Fixed "visitDeathSignal of nonexistent robot"

src/main/battlecode/world/RobotControllerImpl.java
noticed in a couple matches today that unit movement was tweened over the same number of rounds for both rubble and non-rubble movement. the actual movement cooldown appears to use the rubble affected delay, just not the value serialized in the signal.
=> the delay in the movement signal should account for rubble

src/main/battlecode/world/GameWorld.java, src/main/battlecode/world/IDGenerator.java
Resolves https://github.com/battlecode/battlecode-server/issues/220
The case where the parent had ID 0 used to be a special case a long time ago. It's no longer a special case.
Also, now forces all IDs to be positive to comply with specs.
=> Fix bug when there was an archon or den with ID 0

src/main/battlecode/world/GameMap.java, src/main/battlecode/world/control/ZombieControlProvider.java
Opposite zombie dens spawn in opposite directions and chiralities (unless it's a rotationally symmetric map, in which case they spawn with opposite directions and the same chiralities).
=> Make zombies spawns (more) symmetrical

src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java
Debug methods need to return void, not have their names end in the letter V.
=> Fix incredibly dumb typo

src/main/battlecode/common/MapLocation.java, src/test/battlecode/world/RobotControllerTest.java
MapLocation methods didn't check for null, leading to nullPointerExceptions in code that should work. Null direction now basically means "no direction", so "Add distance 5 in direction `null` to location x" results in location x, as opposed to a nullPointerException.
Added tests to confirm functionality.
Resolves #331 
Resolves #334
=> Allow null directions in MapLocation operations

src/main/battlecode/common/BodyInfo.java, src/main/battlecode/common/BulletInfo.java, src/main/battlecode/common/Direction.java, src/main/battlecode/common/GameActionException.java, src/main/battlecode/common/GameActionExceptionType.java, src/main/battlecode/common/GameConstants.java, src/main/battlecode/common/MapLocation.java, src/main/battlecode/common/RobotController.java, src/main/battlecode/common/RobotInfo.java, src/main/battlecode/common/RobotType.java, src/main/battlecode/common/Team.java
Javadocs are in general cleaner and more self-consistent now. A few comments should now be clearer to contestants, some errors have been corrected, and there were also a few leftover references to old functionality (e.g. core delays) that I've now removed.
=> Consistency in javadocs

src/main/battlecode/world/control/PlayerControlProvider.java
Changed robot's random seed to be its own ID, rather than map seed. If IDs weren't already deterministic, then we have another problem.
Resolves #347
=> Unique robot random seeds

src/main/battlecode/common/RobotController.java, src/main/battlecode/world/InternalRobot.java, src/main/battlecode/world/RobotControllerImpl.java, src/test/battlecode/world/RobotControllerTest.java
Someone was getting a nullPointerException when they called `rc.isCircleOccupiedExceptByThisRobot(rc.getLocation(), 3)`. I couldn't replicate it, but I found what should have been causing it and fixed it.
Resolves #357
=> fixed canSensePartOfCircle/canSeseAllOfCircle

src/main/battlecode/server/Config.java, src/main/battlecode/server/NetServer.java, src/main/battlecode/server/Server.java
Resolves https://github.com/battlecode/battlecode-client-17/issues/113 .
Server would sometimes start up, run match, and close before client could establish a connection, thus causing match to not play in client. Added new option for server to block until a client has connected.
=> Better websocket procedures

build.gradle, src/main/battlecode/instrumenter/SandboxedRobotPlayer.java, src/main/battlecode/instrumenter/stream/RoboPrintStream.java, src/main/battlecode/server/Config.java
So that the client build logs won't be super cluttered.
=> Enable estoppel of robot output when running in client

build.gradle
resolves #410.
Turns out SLF4J is necessary to include after all, though it may have a bug; see http://stackoverflow.com/questions/11916706/slf4j-failed-to-load-class-org-slf4j-impl-staticloggerbinder-error . This solution may or may not just be a work-around.
=> silence slf4j output in scaffold

src/main/battlecode/world/GameWorld.java, src/main/battlecode/world/InternalBody.java, src/main/battlecode/world/InternalBullet.java, src/main/battlecode/world/InternalRobot.java, src/main/battlecode/world/ObjectInfo.java, src/main/battlecode/world/RobotControllerImpl.java, src/test/battlecode/world/RobotControllerTest.java
Changes execution order.
Previous: robots > trees > bullets, in order of spawn
Robots and bullets now update during the same "phase", with bullets updating immediately before the robot that fired them. Robots still execute in spawn order, and bullets fired from the same robot also execute in spawn order.
This may need more optimization before being merged, as it potentially doubles the load on the server for running games.
Also, this probably shouldn't be merged before the sprint tournament, as it constitutes a relatively significant change to the layout of the game.
=> Turn order

src/main/battlecode/common/GameConstants.java, src/main/battlecode/common/RobotController.java, src/main/battlecode/common/RobotType.java, src/main/battlecode/instrumenter/bytecode/resources/MethodCosts.txt, src/main/battlecode/world/InternalRobot.java, src/main/battlecode/world/RobotControllerImpl.java, src/test/battlecode/world/RobotControllerTest.java
Unit changes:
* All: Stride radius cut in half
* Tanks: Body attack 2 -> 4, Bullet speed 3 -> 4, Attack power 4 -> 5
* Scout: HP 20 -> 10, Attack power 1 -> 0.5, Sight Radius 10 -> 12
Victory Point Changes:
* Victory point cost starts at 7.5, then increases by 12.5/3000 per round up to 20 at the end of a 3000 round match.
* Current victory point cost can be accessed with rc.getVictoryPointCost()
* Opponent victory points can now be sensed with rc.getOpponentVictoryPoints()
Misc:
* BROADCAST_MAX_CHANNELS increased from 1,000 to 10,000
Tests modified reflect changes in specs.
=> After-sprint spec changes

src/main/battlecode/common/RobotController.java
We now use INTERACTION_DIST_FROM_EDGE instead of stride radius when determining if a robot can interact with a tree. This updates the javadocs accordingly.
=> update tree intereaction javadocs

src/main/battlecode/world/GameWorld.java, src/test/battlecode/world/RobotControllerTest.java
Check for collisions as soon as a bullet is spawned by a unit. This means if two robots are <0.05 apart and one fires a bullet at the other, damage is done immediately (within the robot's turn). This resolves #431 because point-blank combat makes a bit more sense now. In the edge case that this happens to a scout/tree combo, the scout is hit by the bullet and not the tree.
=> Immediate bullet collision check

src/main/battlecode/server/NetServer.java
I spent a long time trying to determine why this exception was occurring, and ultimately determined that it was probably a bug with the websocket library we are using. This fix is hacky and terrible, but at least it silences that damn exception that's been popping up in the client.
=> Silence ClosedByInterruptException on server shutdown.

src/main/battlecode/world/GameWorld.java, src/test/battlecode/world/RobotControllerTest.java
If a tree needs to spawn a robot when it dies, it kills any scouts that would overlap.
Resolves #437
=> Robots can't get stuck on top of each other

src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java, src/main/battlecode/instrumenter/inject/RobotMonitor.java, src/test/battlecode/instrumenter/sample/testplayermultiarraybytecode/RobotPlayer.java
Previously, a multidimensional array with a length 0 component was free to instantiate, regardless of the size of the other components. This can be abused by competitors and used as a free boolean array. This fixes this exploit by treating indices as max(1, index) for the purposes of bytecode computation (the resultant array will still have length 0 components).
=> Fix bytecode computations for arrays of length 0.

src/main/battlecode/instrumenter/TeamClassLoaderFactory.java, src/main/battlecode/instrumenter/bytecode/InstrumentingMethodVisitor.java, src/main/battlecode/instrumenter/inject/ObjectMethods.java, src/main/battlecode/instrumenter/inject/System.java, src/test/battlecode/instrumenter/LoaderTest.java, src/test/battlecode/instrumenter/sample/instrumentertest/DoesntOverrideToString.java, src/test/battlecode/instrumenter/sample/instrumentertest/OverridesToString.java
Object.toString() now returns a deterministic string derived from the same code used for Object.hashCode(), when the toString method is not redefined. This should still work for objects which use the default implementation of toString(), but not for hashCode(), and vice versa.
=> Replace Object.toString() with deterministic version

src/main/battlecode/world/GameWorld.java
On maps where a unit is adjacent to a tree when it is chopped down, this error was throwing because of floating point errors.
=> removed exception
